services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cronoauto
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
 # mongodata:
